apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- bases/clustersize.clusterserviceversion.yaml
- ../manager
- ../rbac
- ../crd

images:
- name: controller
  newName: ghcr.io/rbruzzon73/clustersize-operator
  newTag: v2.0.79
