apiVersion: management.example.com/v1alpha1
kind: ClusterSizeConfig
metadata:
  labels:
    app.kubernetes.io/name: clustersizeconfig
    app.kubernetes.io/instance: clustersizeconfig-sample
    app.kubernetes.io/part-of: clustersize
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: clustersize
  name: cluster-size-config
spec:
  # TODO(user): Add fields here
