apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This forces both files to bind together under the same namespace context
namespace: system

resources:
- manager.yaml
images:
- name: controller
  newName: ghcr.io/rbruzzon73/clustersize-operator
  newTag: v2.0.93
